#!/bin/bash
# By @hiukky https://hiukky.com

declare flag=$(echo "$@")

IF=$(ip -o link show | awk -F': ' '{print $2}' |  head -2 | tail -1)

while true
do
    R1=`cat /sys/class/net/$IF/statistics/rx_bytes`
    T1=`cat /sys/class/net/$IF/statistics/tx_bytes`

    sleep 1

    R2=`cat /sys/class/net/$IF/statistics/rx_bytes`
    T2=`cat /sys/class/net/$IF/statistics/tx_bytes`

    TBPS=`expr $T2 - $T1`
    RBPS=`expr $R2 - $R1`

    TKBPS=`expr $TBPS / 1024`
    RKBPS=`expr $RBPS / 1024`

    case $flag in
    '-up')
        echo "$TKBPS kb/s";;
    '-down')
        echo "$RKBPS kb/s";;
     *)
        echo "up $TKBPS kb/s   down $RKBPS kb/s";;
    esac
done
